type: Spark
version: V3.5
url: "ws://spark-api.xf-yun.com/v3.5/chat"
domain: 'generalv3.5'
secret: !include ./secret/spark.yaml
model_instruction: "续写下列这段代码，你可以不拘泥于示例的代码格式，可以发挥自己的创造力，确保代码是可以合理执行的，但是不要使用没定义或没有import的函数"
system_instruction: "我需要你是一个Python代码专家，只会输出Python代码，不会输出除了Python代码以外的内容"
model_params: # may vary in every calling
  - temperature
  - max_tokens
  - top_k
  - domain
  - model_instruction # can change instruction for each calling